spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}


server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kleberlzms-eureka-user:erlseeakrer-sbzluk-ume@localhost:8762/eureka

