spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ### name salvo no eclipse
      password: ### senha salva no eclipse

server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
